export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const SET_COLOR_LIST = 'SET_COLOR_LIST';
export const SET_COLOR = 'SET_COLOR';
export const SAVE_COLOR = 'SAVE_COLOR';
export const OPEN_SAVE_COLOR_MODAL = 'OPEN_SAVE_COLOR_MODAL';
export const CLOSE_SAVE_COLOR_MODAL = 'CLOSE_SAVE_COLOR_MODAL';
